# Reference:
# https://github.com/openzipkin/zipkin/tree/master/docker/examples

version: "3.8"

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to.
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./server
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 4003:4003
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - zipkin
    env_file:
      - ./server/.env
    command: npm start
